### ISSUE TITLE
CSV Hosts Import

### ISSUE THREAD

**Issue by luisvalleGH** [Vadims06/topolograph#10]
Hi Vadims

I'm trying to import host names with the CSV import feature
I get the not valid IP error, i think i'm not understanding the documentation maybe, you put

"Enter the list of headers followed by one line per record to be imported, using commas to separate values. Device's hostnames will be changed for choosed graph's time."

What do you mean about headers

This is what i'm typing in the import text box

172.16.254.0,La Union (CCR1016)
172.16.254.2,CCR1_CCR1016
172.16.254.3,La Union PowerBox 1 (Vinculos)
172.16.254.4,La Union PowerBox 2 (APs)
172.16.254.5,Powerbox Aparicio (Vinculos)

Thank you for the time, the app is really good

**Comment by Vadims06** [comment]
> Hi Vadims
> 
> I'm trying to import host names with the CSV import feature
> I get the not valid IP error, i think i'm not understanding the documentation maybe, you put
> 
> "Enter the list of headers followed by one line per record to be imported, using commas to separate values. Device's hostnames will be changed for choosed graph's time."
> 
> What do you mean about headers
> 
> This is what i'm typing in the import text box
> 
> 172.16.254.0,La Union (CCR1016)
> 172.16.254.2,CCR1_CCR1016
> 172.16.254.3,La Union PowerBox 1 (Vinculos)
> 172.16.254.4,La Union PowerBox 2 (APs)
> 172.16.254.5,Powerbox Aparicio (Vinculos)
> 
> Thank you for the time, the app is really good

Hi @luisvalleGH, thank you for your feedback.
During CSV importing - keep headers in the first line, something like that
```device_ip_address,device_name```
```123.123.100.100,La Union (CCR1016)```

I hope it will work for you

**Comment by luisvalleGH** [comment]
Works like a charm, sorry to have bother you with something so easy, my understanding fo the documentation has been very poor.

Closed
