### ISSUE TITLE
New textfsm templates for Paloalto PANOS available

### ISSUE THREAD

**Issue by perw07** [Vadims06/topolograph#11]
Hi!

I have made templates for Paloalto PANOS. How do I easiest hand them over for you to take a look at?

**Comment by Vadims06** [comment]
Hi @perw07, What a great news!
I would be grateful if you send it to admin@topolograph.com as well as `LSDB LSA1, LSA2, LSA5 outputs` files.

**Comment by Vadims06** [comment]
PaloAlto support has been implemented in v2.18. Thanks @perw07 !
