### ISSUE TITLE
ISIS Database Integration

### ISSUE THREAD

**Issue by arshaans** [Vadims06/topolograph#15]
Hi,
Is it possible to Integrate this Tool with ISIS database as both are Link State Routing Protocols using the Dijkstra SPF Algorithm

**Comment by Vadims06** [comment]
Good point @arshaans, but I'm planning to finish implementing features for OSPF and then I need to consulate with IS-IS experts about protocol specific details.

**Comment by arshaans** [comment]
I was going through the code implementation, however I did not see the flask middleware code in the repo

Thanks

**Comment by Vadims06** [comment]
@arshaans IS-IS is implemented in the latest release)
