### ISSUE TITLE
HP support

### ISSUE THREAD

**Issue by flemin-ctrl** [Vadims06/topolograph#16]
Would like to see support for HP / Comware. Can't upload TextFSM files as it's a secure environment.

**Comment by Vadims06** [comment]
Hi @flemin-ctrl, 
Do you mean that TextFSM is located in a secure environment and you cannot share it or you cannot share LSA1/LSA2/LSA5 OSPF outputs? I can build TextFSMs for HP, but I need OSPF outputs even with obfuscated IP addresses. Let's leave your request open and wait, probably someone can share it with us.

**Comment by Vadims06** [comment]
Hi @flemin-ctrl , HP support is implemented in topolograph v2.22. Please check it.
It worth to mention that HP output misses some valuable details, specifically subnet mask for stub and external networks. I am looking forward to hearing feedback from you.

**Comment by Vadims06** [comment]
HP's LSDB output is not follow RFC2328 that's why it cannot be added to Topolograph. As a workaround I suggest to boot up the Quagga and establish an OSPF adjacency with HP
