### ISSUE TITLE
Cisco IOS-XR ospfv3 database is not supported

### ISSUE THREAD

**Issue by sergedevorop** [Vadims06/topolograph#2]
Not sure which cisco devices CLI/outputs are supported and which are not.
At least IOX XR ospv3 database upload does not get any results.

**Comment by Vadims06** [comment]
Hi @sergedevorop . Thank you for giving the feedback. You know, I just tested it on ospfv2 version, which is generally used. If you could send me your command outputs on admin@topolograph.com - I would try to create templates for OSPFv3. I will appreciate it.

**Comment by Vadims06** [comment]
@sergedevorop, I added a table with expected commands. Hope you will find this helpful.
