### ISSUE TITLE
Code not in repo

### ISSUE THREAD

**Issue by forkwhilefork** [Vadims06/topolograph#21]
Unless I am missing it, the code is not actually in this repository. Is that an oversight? How can I view and contribute to the source?

**Comment by Vadims06** [comment]
Hi @forkwhilefork, thank you for your interest. Yes, this repository doesn't contain the source code. Write me at admin at topolograph.com and we find a way how to contribute to the source.

**Comment by forkwhilefork** [comment]
Okay, I've sent you an email.
