### ISSUE TITLE
AlliedWare+ support

### ISSUE THREAD

**Issue by soloduy1** [Vadims06/topolograph#22]
I use many AT x900 routers in my network, can you add support them? I will provide the examples commands if needed.

**Comment by Vadims06** [comment]
Hi @soloduy1 , thanks for your request. I need an output, which describes your OSPF domain, something similar to 'show ip ospf database router details', ‘show ip ospf database network details’, ‘show ip ospf database external details’. Based on this I will try to add AlliedWare support.

**Comment by Vadims06** [comment]
@soloduy1 implemented
