### ISSUE TITLE
Ability to review source code

### ISSUE THREAD

**Issue by haydenseitz** [Vadims06/topolograph#27]
I found your project recently and would like to contribute. Is the source available for review? 

Thanks!

**Comment by haydenseitz** [comment]
My company has developed a similar tool that displays devices and their routing information, but on a geographical map with lat/lng coordinates. The OSPF data comes from a monitoring system that collects SNMP data. However, collecting data directly from the OSPF tables on the routers is a better strategy.

I'm interested in adding a geographical map that can display the same data. I have most experience with [leaflet ](https://leafletjs.com/) map tools

**Comment by Vadims06** [comment]
@haydenseitz sound impressive! I've send you the invitation. Please make a branch from v2.26.

**Comment by Vadims06** [comment]
Hi @haydenseitz, do you find it still relevant for you?

**Comment by haydenseitz** [comment]
@Vadims06 I have not been able to dedicate much time to development on this project

**Comment by FloLaco** [comment]
Hello @Vadims06 ,
What's your LICENSE about your code, and can you share it (make it open source ?).
I'm thinking for a project to build a network layer 3 topology but with only routing table because we use various routing protocol (bgp, ospf, is-is, and a lot of static).
I try to not reinvent the wheel

**Comment by Vadims06** [comment]
Hi @FloLaco, you can use free docker-based Topolograph or contribute to the source code. The design of Topolograph is slightly different to what you are thinking about, Topolograph needs a single connection to a device in each area ( but also works with offline data ) to get LSDB, to get static routes - it's needed to connect to each device and update this information periodically. IS-IS is the next in my plan. By the way, I think SuzieQ does what you looking for, check it and give me update if it works for you. If not, you can scrap information from your devices and build the topology using Topolograph via API ( I can introduce such feature )
