### ISSUE TITLE
self-hosted?

### ISSUE THREAD

**Issue by reinethernal** [Vadims06/topolograph#3]
Hi! Is there any way to run this app at my servers?

**Comment by Vadims06** [comment]
> Hi! Is there any way to run this app at my servers?

Hi @reinethernal, 
Absolutely! Docker's version of topolograph is available. You just need to setup Docker-CE on your host. Win/Linux is supported and it's free. Then pull topolograph container and get profit! Docker version of site is here https://github.com/Vadims06/topolograph-docker

**Comment by reinethernal** [comment]
Yay!! Thank you))
