### ISSUE TITLE
Cisco XR IS-IS Build Path function is is not showing

### ISSUE THREAD

**Issue by sayyod1981** [Vadims06/topolograph#30]
I made some corrections  in textfsm template file to load Cisco XR IS-IS database. After this It started to load topology correctly, but when I click Build the shortest path it is not showing any reports.   I will appreciate it, if you will give some solution.
Thanks in advance!

**Comment by Vadims06** [comment]
Hi @sayyod1981,
Thank you for your feedback. I will be glad to help. Could you please probably share a sample of your topology (ISIS LSDB txt file) and what changes you made in Cisco XR templates. If so, you can send them on admin @ topolograph.com email.

**Comment by sayyod1981** [comment]
Please, kindly check your email. I send you all necessary files.

**Comment by Vadims06** [comment]
Hi @sayyod1981,
Fix it in v2.26.3 version. It was needed to change ISIS template slightly for Cisco devices. 
If you have something what you can share about your experience of using Topolograph, improvements - I will appreciate it.

**Comment by sayyod1981** [comment]
Hi! Yes, now it is working! 
Thank you!
