### ISSUE TITLE
Support for importing Cisco NX-OS DB

### ISSUE THREAD

**Issue by kirk444** [Vadims06/topolograph#31]
I believe the IOS and NX-OS output are sufficiently different that the "Cisco OSPF" import from text fails. I think it may simply be a difference in column names, for example:

LSA1:
```
        OSPF Router with ID (0.0.0.0) (Process ID 1 VRF default)

                Router Link States (Area 0.0.0.0)

Link ID         ADV Router      Age        Seq#       Checksum Link Count
```

LSA2:
```
        OSPF Router with ID (0.0.0.0) (Process ID 1 VRF default)

                Network Link States (Area 0.0.0.0)

Link ID         ADV Router      Age        Seq#       Checksum

```
LSA5:
```
        OSPF Router with ID (0.0.0.0) (Process ID 1 VRF default)

                Type-5 AS External Link States

Link ID         ADV Router      Age        Seq#       Checksum Tag
```

**Comment by Vadims06** [comment]
Hi @kirk444 , thank you for this feedback. 
Yeah, I guess it has different output and I will be happy to add NX-OS support into Topolograph. Could you please send the samples of LSA1,2 and 5 at admin at topolograph.com? Or if you feel confident to fix existed templates by yourself I would be also grateful for getting textfsm templates. I will add them to Topolograph.

**Comment by kirk444** [comment]
Here's the same output with some sample data in it, is this sufficient?


`        OSPF Router with ID (208.79.224.2) (Process ID 1 VRF default)

                Router Link States (Area 0.0.0.0)

Link ID         ADV Router      Age        Seq#       Checksum Link Count
10.83.83.1      10.83.83.1      405        0x800018a1 0x11b2   3
10.86.86.1      10.86.86.1      1364       0x80006431 0x434c   3
10.255.254.82   10.255.254.82   159        0x80007b51 0xea46   7
10.255.254.83   10.255.254.83   313        0x80007b04 0x18a2   6
192.168.11.1    192.168.11.1    929        0x80009b73 0x0810   3
192.168.36.1    192.168.36.1    684        0x80007c40 0xb35e   4
192.168.70.1    192.168.70.1    504        0x8000bb5f 0x52d2   3
`

`        OSPF Router with ID (208.79.224.2) (Process ID 1 VRF default)

                Network Link States (Area 0.0.0.0)

Link ID         ADV Router      Age        Seq#       Checksum
10.11.12.100    208.79.224.29   1099       0x80005276 0x4e67
10.11.12.102    208.79.224.30   1442       0x800060cc 0x83c7
10.11.12.104    208.79.224.30   1160       0x800027f2 0xc09c
10.11.12.109    208.79.224.27   1517       0x800041cf 0x5219
10.11.12.114    208.79.224.26   1107       0x800027f2 0x401d
10.11.12.116    208.79.224.29   1269       0x80005276 0x218e
10.11.12.121    208.79.224.17   69         0x80005277 0x7341
10.11.12.200    208.79.224.17   409        0x80005f92 0x267e
10.11.12.203    10.86.86.1      1107       0x800041d0 0xbc16
10.11.13.100    208.79.224.8    1519       0x80002561 0x6bcb
10.11.13.102    208.79.224.8    1119       0x80002562 0x63cf
10.21.32.101    208.79.224.19   9          0x80005698 0xeba3
10.83.254.101   208.79.224.25   56         0x80002bde 0xbe86
10.83.254.103   208.79.224.22   1787       0x8000025d 0x39b8
10.83.254.106   208.79.224.22   1258       0x8000189e 0x8876
`

`        OSPF Router with ID (208.79.224.2) (Process ID 1 VRF default)

                Type-5 AS External Link States

Link ID         ADV Router      Age        Seq#       Checksum Tag
10.0.2.0        208.79.224.6    1107       0x80001be2 0x07bb    2804
10.1.0.0        208.79.224.6    1107       0x80001be2 0x11b2    2804
10.7.113.0      208.79.224.5    1074       0x8000325d 0xb3cf    65080
10.10.40.0      208.79.224.17   574        0x80001315 0xf0c5    11640
10.10.40.0      208.79.224.29   524        0x80001315 0xa802    11640
10.10.100.0     208.79.224.17   574        0x80001315 0x5a20    11640
10.10.100.0     208.79.224.29   524        0x80001315 0x125c    11640
10.12.10.0      208.79.224.17   114        0x80005f8e 0x0c95    20424
10.12.10.16     208.79.224.20   1260       0x800021d8 0x7f03    20424
`

**Comment by Vadims06** [comment]
Hi @kirk444 ,
it looks like `show ip ospf database` command's output. `show ip ospf database router detail` has a different format, are you sure that it is `show ip ospf database router/network/external detail`command?

**Comment by kirk444** [comment]
Sorry, that's the output from the commands mentioned for Cisco IOS. Detail output:
```
# show ip ospf database router detail
        OSPF Router with ID (x.x.x.x) (Process ID 1 VRF default)

                Router Link States (Area 0.0.0.0)

   LS age: 59
   Options: 0x2 (No TOS-capability, No DC)
   LS Type: Router Links
   Link State ID: 10.83.83.1
   Advertising Router: 10.83.83.1
   LS Seq Number: 0x80001967
   Checksum: 0x827a
   Length: 60
    Number of links: 3

     Link connected to: a Stub Network
      (Link ID) Network/Subnet Number: 10.83.83.0
      (Link Data) Network Mask: 255.255.255.0
       Number of TOS metrics: 0
         TOS   0 Metric: 40

     Link connected to: a Stub Network
      (Link ID) Network/Subnet Number: 10.83.83.0
      (Link Data) Network Mask: 255.255.255.0
       Number of TOS metrics: 0
         TOS   0 Metric: 40

     Link connected to: a Transit Network
      (Link ID) Designated Router address: 10.83.254.106
      (Link Data) Router Interface address: 10.83.254.107
       Number of TOS metrics: 0
         TOS   0 Metric: 20

   LS age: 997
   Options: 0x2 (No TOS-capability, No DC)
   LS Type: Router Links
   Link State ID: 10.86.86.1
   Advertising Router: 10.86.86.1
   LS Seq Number: 0x800064f7
   Checksum: 0xb513
   Length: 60
    Number of links: 3

     Link connected to: a Stub Network
      (Link ID) Network/Subnet Number: 10.86.86.0
      (Link Data) Network Mask: 255.255.255.0
       Number of TOS metrics: 0
         TOS   0 Metric: 40

     Link connected to: a Transit Network
      (Link ID) Designated Router address: 10.11.12.203
      (Link Data) Router Interface address: 10.11.12.203
       Number of TOS metrics: 0
         TOS   0 Metric: 10

     Link connected to: a Transit Network
      (Link ID) Designated Router address: 10.11.12.200
      (Link Data) Router Interface address: 10.11.12.201
       Number of TOS metrics: 0
         TOS   0 Metric: 10

```

```
# show ip ospf database network detail
        OSPF Router with ID (x.x.x.x) (Process ID 1 VRF default)

                Network Link States (Area 0.0.0.0)

   LS age: 852
   Options: 0x2 (No TOS-capability, No DC)
   LS Type: Network Links
   Link State ID: 10.11.12.100 (Designated Router address)
   Advertising Router: x.x.x.x
   LS Seq Number: 0x8000533c
   Checksum: 0xbf2f
   Length: 32
   Network Mask: /31
         Attached Router: x.x.x.x
         Attached Router: x.x.x.x

   LS age: 1201
   Options: 0x2 (No TOS-capability, No DC)
   LS Type: Network Links
   Link State ID: 10.11.12.102 (Designated Router address)
   Advertising Router: x.x.x.x
   LS Seq Number: 0x80006192
   Checksum: 0xf48f
   Length: 32
   Network Mask: /31
         Attached Router: x.x.x.x
         Attached Router: x.x.x.x
```

```# show ip ospf database external detail
        OSPF Router with ID (x.x.x.x) (Process ID 1 VRF default)

                Type-5 AS External Link States

   LS age: 927
   Options: 0x2 (No TOS-capability, No DC)
   LS Type: Type-5 AS-External
   Link State ID: 10.0.2.0 (Network address)
   Advertising Router: x.x.x.x
   LS Seq Number: 0x80001ca8
   Checksum: 0x7883
   Length: 36
   Network Mask: /24
         Metric Type: 2 (Larger than any link state path)
         TOS: 0
         Metric: 1
         Forward Address: 0.0.0.0
         External Route Tag: 2804

   LS age: 927
   Options: 0x2 (No TOS-capability, No DC)
   LS Type: Type-5 AS-External
   Link State ID: 10.1.0.0 (Network address)
   Advertising Router: x.x.x.x
   LS Seq Number: 0x80001ca8
   Checksum: 0x827a
   Length: 36
   Network Mask: /16
         Metric Type: 2 (Larger than any link state path)
         TOS: 0
         Metric: 1
         Forward Address: 0.0.0.0
         External Route Tag: 2804

   LS age: 896
   Options: 0x2 (No TOS-capability, No DC)
   LS Type: Type-5 AS-External
   Link State ID: 10.7.113.0 (Network address)
   Advertising Router: x.x.x.x
   LS Seq Number: 0x80003323
   Checksum: 0x2597
   Length: 36
   Network Mask: /24
         Metric Type: 2 (Larger than any link state path)
         TOS: 0
         Metric: 1
         Forward Address: 0.0.0.0
         External Route Tag: 65080

```

**Comment by Vadims06** [comment]
Did you try to save it into a single file and upload to Topolograph?

**Comment by kirk444** [comment]
Yeah, they return "The graph is empty. Are you sure, that you uploaded OSPF LSDB from Cisco?"

**Comment by Vadims06** [comment]
Got it, I will check it

**Comment by Vadims06** [comment]
Fixed some tiny differences: 
1. `Metrics:` -> `Metric:`
2. `network/subnet Number:` -> `Network/Subnet Number:`
Please test it on v2.29.1 version and give me an update.
Could you also please configure one link as `point-to-point` and re-send me `show ip ospf database router detail` again?

**Comment by kirk444** [comment]
The import now completes successfully from `show ip ospf database router detail`, but not from either network or external.

I don't think the import is correct in the case that it imports, it seems to generate the nodes and the networks properly, but no paths are displayed in the output, just the nodes/dots.


For the "point-to-point" topic, I can not change any of these existing links, but I will try to set something up in a test network to generate the output you're looking for.

**Comment by Vadims06** [comment]
Hi @kirk444 , did you upload only single file with router detail output?
It's needed to save the outputs from three commands into the single txt file and upload it into the Topolograph...

**Comment by kirk444** [comment]
Yup, I sure did! That definitely helps answer my question about how this was supposed to work with only one of those views! This appears to be working just fine in 2.29.1, once I imported correctly (all outputs in one file). Sorry for the confusion.
