### ISSUE TITLE
Request to add compatibility for Extreme Networks switches

### ISSUE THREAD

**Issue by lookwhatyouvegoneanddone** [Vadims06/topolograph#33]
Hi there,

I noticed the list of compatible vendors is fairly comprehensive, I was wondering if it would be possible to add Extreme Networks LSDBs to the list? Would this be difficult to do?

**Comment by lookwhatyouvegoneanddone** [comment]
Hey thanks for the response.

Just sent you an email, was hoping for OSPF support if possible. Let me know if you need anything else.

**Comment by Vadims06** [comment]
Hi @lookwhatyouvegoneanddone ,
I've just released v2.32 (latest) version with Extreme support. Could you please confirm that it works correctly?

**Comment by alchemyx** [comment]
Apologies for chiming in but it seems that Extremes support for OSPF is working beautifully, I just confirmed on few X460 and X670.

**Comment by Vadims06** [comment]
@alchemyx Thanks a lot for confirming and thanks @lookwhatyouvegoneanddone for your help to build templates!
