### ISSUE TITLE
Arista OSPF(v3) support

### ISSUE THREAD

**Issue by RaidAndFade** [Vadims06/topolograph#35]
Hello, I found this project recently and love the concept, we run Arista and would love to know if that's a planned supported platform and if not what steps are required to help you implement it.

**Comment by Vadims06** [comment]
Hi @RaidAndFade , thank you cutting this feature request. I will be glad to onboard Arista. Are you interested in OSPFv3 or v2? If so I will need the output of three commands:
* show ip ospf database router detail
* show ip ospf database network detail
* show ip ospf database external detail
Can you send me the output directly to admin @ topolograph.com?

**Comment by RaidAndFade** [comment]
@Vadims06, Thanks for the quick response.

Arista does not seem to split up the options, we use OSPFv3 and the command to get *all* LSAs is `show ospfv3 database detail`

I've sent you our output directly to the specified email, please let me know if you need anything else on our end. Appreciate the good work!

**Comment by Vadims06** [comment]
OSPFv3 is onboarded for Arista in v2.35
