### ISSUE TITLE
D-link support?

### ISSUE THREAD

**Issue by reinethernal** [Vadims06/topolograph#4]
One more question - how about d-link support?)

**Comment by Vadims06** [comment]
> One more question - how about d-link support?)

@reinethernal, actually no) The actual list of supported vendors is mentioned in Readme file. For all unsupported vendors is available option with free FRR/Quagga. It suggested to setup a Quagga on a Linux host and establish adjacency over GRE tunnel. Then it's feasible to get LSDB of your network from Quagga.
