### ISSUE TITLE
IS-IS topology from Cisco IOS-XR

### ISSUE THREAD

**Issue by lemontree61089** [Vadims06/topolograph#42]
Hello,

Is IS-IS topology from Cisco IOS-XR supported?
I just tested it and I got "The graph is empty. Are you sure, that you uploaded ISIS LSDB from Cisco?"

Thanks!

**Comment by Vadims06** [comment]
Hey @lemontree61089 ,
I tested IS-IS on general Cisco IOS versions, not IOS-XR. I bet that it might be slightly different from IOS version. I can check and change IS-IS templates. May I ask you to send me your IS-IS LSDB output to admin at topolograph.com?..

**Comment by Vadims06** [comment]
@lemontree61089 , thank you for providing LSDB. I changed IS-IS templates appropriately. Please check and give me feedback.

**Comment by lemontree61089** [comment]
It works well now. Thanks for the quick support!
