### ISSUE TITLE
largest map-able ospf datasbase?

### ISSUE THREAD

**Issue by spacklePatch** [Vadims06/topolograph#43]
Is there a size limit for the numbers of nodes in area 0? I currenty tried a large network (1700+ nodes) and nothing would load.

**Comment by Vadims06** [comment]
Hi @spacklePatch,
wow, 1700+ nodes! Actually I tested on 0.5k nodes and it works. I can admit, that there is no any limits for the number of nodes. May I ask you to send this LSDB to admin @ topolograph.com?.. If it's not possible, I will try to generate a graph with similar size.

**Comment by Vadims06** [comment]
tested on 1600 nodes.
Could you please provide some more context: do you upload LSDB via text file or create a network via "Create Topology" and yaml file? Do you see a loading bar, when you press "Load dynamic graph"?
![image](https://github.com/Vadims06/topolograph/assets/20796986/f47c5f43-f2c6-4dbc-919f-686129c6e6e4)

**Comment by spacklePatch** [comment]
I uploaded a Mikritok LSB file from router os 7.3.1.  I have other versions and a few other router models I can try. I'm still waiting to see if I can send the actual file I used. I don't see anything happening when I press the "Load dynamic graph" button. I'll keep you informed

**Comment by Vadims06** [comment]
It's beautiful! I will be glad if reports about asymmetric links and paths help you, as well as building paths and find backups, etc!
I suppose that Mikrotik changed LSDB output in `7.3.1`, I could try to fix templates for new version if you can share a small peace of it, but if it's not crucial and it works with `6.48.6`, it's okay. All in all I will try to evaluate how much memory and other resources are required to work with such big graphs!

**Comment by spacklePatch** [comment]
I'm still waiting to see if the company will let me release the LSADB (nothing secret in there, but i have to verify). In the mean time, I upgraded one of my small routers at my house (yes, I have OSPF running in my home network), with a before/after  DB export. I do believe it's mostly a formatting change between versions:
 
[lsa-ROS-6.48.6.txt](https://github.com/Vadims06/topolograph/files/12819055/lsa-ROS-6.48.6.txt)
[lsa-ROS-7.10.txt](https://github.com/Vadims06/topolograph/files/12819056/lsa-ROS-7.10.txt)

**Comment by Vadims06** [comment]
thank you for the provided output. I compared it and they differ, i.e 
| 6.48 | 7.10 |
|------|------|
| type=router | type="router" |
| Stub 192.168.43.0 | type=stub id=192.168.43.0 |

but good news is that current templates match both options. I fixed only pattern for external subnet. Let me clarify the problem once again - if you upload either `6.48` or `7.10` LSDB output  and graph name with date and number of hosts appears in your list - it means that parsing was successful. If you press the "Load dynamic graph" button and can see the topology for `6.48`, but not for `7.10` it means that something happened during topology generation. If so - could please check any errors in browser console ( available via F12 ).

**Comment by spacklePatch** [comment]
With a RoS 6.49 LSDB file,everything works as expected. RoS 7 significantly changed the output. This causes nothing to happen when I press the "Load dynamic graph". The browser console log does theow and error when I do this, it is attached.

Peter Robbins
Network  Engineer
[signature_770029387]
855.NXT.LINK (855.698.5465)

**Comment by Vadims06** [comment]
@spacklePatch, I afraid that attached error was not attached to your comment if you replied via your email.

**Comment by Vadims06** [comment]
Hi @spacklePatch ,
thanks to @moghue42, I applied fix for ROS 7.10, please check if your LSDB works properly

**Comment by Vadims06** [comment]
Confirmed by @moghue42
