### ISSUE TITLE
DB graphing 

### ISSUE THREAD

**Issue by spacklePatch** [Vadims06/topolograph#44]
Can this draw a static map (one that doesn't move the nodes around all the time) with minimal overlapping paths, and highlight the default path originator ?

**Comment by Vadims06** [comment]
This button allows to "freeze" a diagram and all nodes, they won't be moving.
![image](https://github.com/Vadims06/topolograph/assets/20796986/2c4db3ec-3e31-459c-baed-5ec4187aca5b)
Could you please clarify what highlight the default path originator means?..

**Comment by spacklePatch** [comment]
If a default router (0.0.0.0/0, there should only be one) is advertised from a router in the LSA, highlight that node in a different size or color.

**Comment by Vadims06** [comment]
There is an option to search by network and Focus on the node. Acknowledge that `Focus/From` should be renamed or network lookup should be allocated in a separate field. Will it be just enough to rename to something like `Query by node/network` and then change node's color? Do you have cases when you need to find all nodes where subnets with `/0` or less/more than `/<whatever size>` is located?
![image](https://github.com/Vadims06/topolograph/assets/20796986/bc1442e7-4d72-4382-a88f-f4e6677a8dc0)

**Comment by spacklePatch** [comment]
Ideally, only one router in a network should advertise a default route (assuming it’s just OSPF, and not in iBGP or something). I’d just like a way to make that router easily visible. That router is probably the core of the network. If more than one router advertises a default route, there is probably a configuration issue to resolve.

Peter Robbins
Network  Engineer
[signature_770029387]
855.NXT.LINK (855.698.5465)
