### ISSUE TITLE
Mikrotik Routeros 7.x Graphing

### ISSUE THREAD

**Issue by moghue42** [Vadims06/topolograph#45]
I've done some extensive searching to see if there was something I was missing. When I upload a lsdb of a Routeros7.14 router I cannot get any sort of graphing. It parses the information and acts like a graph is available however it will not load the graph itself.

Is there anything I can do to translate it to work within existing confines?

**Comment by Vadims06** [comment]
Hi @moghue42 ,
> It parses the information and acts like a graph is available
Is it fair to say that after uploading LSDB you see that new row appears in a drop-down list with date and number of devices in a area as a name, but a graph doesn't appear?
What version Topolograph do you use?
Could you please also open Console via F12 in Google chrome and check if any errors appears in it after pressing Upload button?

**Comment by moghue42** [comment]
I've tried from the bottom up. I uploaded a smaller os7 file and it worked okay so I am now thinking the file I have is too large. This is giving me a internal server error 500. Im using the web version of topolograph. I removed all existing graphs and tried to upload a fresh export and it too gives a "https://topolograph.com/upload-ospf-lsdb-from-js 500 (Internal Server Error)"

**Comment by Vadims06** [comment]
I tried to recreate an issue using Mikrotik's samples what I have, but couldn't do it. May I ask you to send me your LSDB on my mail: admin at topolograph.com?..

**Comment by Vadims06** [comment]
I found that previous Issue also mentioning a problem with loading ROS7 https://github.com/Vadims06/topolograph/issues/43#issuecomment-1753061919, but since I didn't have example, I couldn't resolve it. I hope that you have an chance to send ROS 7 output.

**Comment by Vadims06** [comment]
Thank you for providing LSDB. I applied fix for ROS 7.10, please check
