### ISSUE TITLE
Issue with point-to-point OSPF adjacency (Cisco Nexus OSPF)

### ISSUE THREAD

**Issue by kirk444** [Vadims06/topolograph#47]
I have a network (mixed Cisco Nexus and FRR, import as Quagga seems to work) OSPF nodes. When I import the LSDB from a Cisco Nexus device any adjacencies that are of type ospf point-to-point fail to import. Links that are ospf type broadcast import correctly.

If I take LSDB for the same network from FRR (import as quagga) all point-to-point and broadcast type links are imported correctly.

**Comment by Vadims06** [comment]
I applied fixed for p2p links and made a release v2.39. Docker version `vadims06/topolograph:2.39` is also available. Please check

**Comment by kirk444** [comment]
I can confirm the new version works as intended, thank you!
