### ISSUE TITLE
How are nodes and links build from an ospf database

### ISSUE THREAD

**Issue by ObaidAshiq** [Vadims06/topolograph#50]
i am building an ospf visualizer kind of thing in react
As far as i have researched, 
You need 3 data things, from the terminal of a router
And that we can get from these commands
`show IP ospf database`
`show ip ospf database router`
`show ip ospf database network`
You might also need 
`show ip ospf database external` which I am skipping not to increase the complexity of my project

The problem I am facing is how to create those arrays of nodes and links ?
If u could guide me through, would be a great help

[Youtube Video](https://www.youtube.com/watch?v=6EIdx1j6FMw)

**Comment by Vadims06** [comment]
Hi @ObaidAshiq ,
it's quite interesting question. Feel free [wiki page](https://github.com/Vadims06/topolograph/wiki/How-to-add-new-vendor-support) describing onboarding process of new vendors into Topolograph, I described the idea how to parse the output of these commands. But the youtube video attached also discovered this idea as well. 
Also you can use topolograph [API ](https://topolograph.com/api/ui/) and get an array of nodes and links in its reply.
I would be grateful if you also share what it's your end goal from your visualizer, do you want to visualize OSPF from the vendor currently not supported by Topolograph or as a coding practice?
