### ISSUE TITLE
DNS for big networks

### ISSUE THREAD

**Issue by laimaretto** [Vadims06/topolograph#7]
Hi! So if I have a small network, I can then go to the DNS section and type in the names of the routers.

But I've been trying some big networks (+500 nodes) and doing so by hand is rather a difficult task.

![image](https://user-images.githubusercontent.com/8891825/107698839-eef5a380-6c93-11eb-8910-744259d26a43.png)

Is there another option to accomplish this? May be I'm missing something ... 

Thanks!

**Comment by Vadims06** [comment]
Hi @laimaretto. If you use topolograph container there is `docker-compose.override.yml` file where you can set DNS IP address. After this when you upload hosts next time - their OSPF RID will be changed by their names.
Please check files structure in topolograph container [repo](https://github.com/Vadims06/topolograph-docker)

**Comment by laimaretto** [comment]
Hi @Vadims06 . Yes, I'm using the docker version and I've seen how to set up the DNS IP address in the `docker-compose.override.yml` file. Thanks for that. I was wondering if there was a chance of using, for example, the `/etc/hosts` file or reading a local file, which is simpler than setting up a local DNS server (like bind).
I will however have a look on how to install a local dns server in my laptop ... 
thanks again! cheers!

**Comment by Vadims06** [comment]
@laimaretto, you know, because of a container nature- container's processes are separated from host's files, disks, or network. That's why topolograph's app doesn't have access to /etc/hosts of the host's server. Actually, I came up with another idea. Probably you have DCIM system like Netbox. If so it feasible to get domain name binding from that system.

**Comment by laimaretto** [comment]
@Vadims06 , I like the idea of using a DCIM. I don't have Netbox, however I do have RackTables, for the same purpose. I can gather information from RackTables by means of SQL ... would that work?

**Comment by Vadims06** [comment]
@laimaretto, I though that I could write API connector to RackTables, but as it was discovered RackTables has API to his SQL database ( rather strange solution ). So I implemented CSR Import option
![image](https://user-images.githubusercontent.com/20796986/110693329-5e5da500-81f8-11eb-86fb-cee392bcc7ed.png)
where you can paste exported from RackTables data in CSV format `10.1.1.1,router_1`
![image](https://user-images.githubusercontent.com/20796986/110693682-c14f3c00-81f8-11eb-8c98-2620289c5577.png)
When import has been finished - required hostnames will be saved in Topolograph ;)
![image](https://user-images.githubusercontent.com/20796986/110693870-fcea0600-81f8-11eb-9fee-8c7595bb7747.png)

**Comment by Vadims06** [comment]
Hi @laimaretto, Just for you info - I released topolograph:v2.17 where I added assignment devices to their groups and then - color graph.
![v2 17](https://user-images.githubusercontent.com/20796986/114076442-57858900-98af-11eb-9653-74374302ef2d.png)
So I'm closing this Issue. I was glad to work on it.

**Comment by Vadims06** [comment]
Hi @laimaretto, thank you for your feedback! Be in touch!
