### ISSUE TITLE
Mikrotik Support

### ISSUE THREAD

**Issue by nlgotz** [Vadims06/topolograph#8]
Hello,

Are there any plans to add support for Mikrotik routers? I can provide the necessary database outputs if needed.

Thanks!

**Comment by Vadims06** [comment]
Hi @nlgotz, thank you for your request. Sure, I need the output describing LSA1, LSA2, LSA5. Please send me the output to admin@topolograph.com

**Comment by rinchen** [comment]
I have LSAs and Routes in a text file to send you but the email above is bouncing and I can't seem to create an account on your slack. I don't want to push my routes in a public github ticket.

**Comment by Vadims06** [comment]
> I have LSAs and Routes in a text file to send you but the email above is bouncing and I can't seem to create an account on your slack. I don't want to push my routes in a public github ticket. Please advise.

Hi @rinchen , sure, but let me clarify, if you send the email to admin@topolograph.com - you get an error?..

**Comment by Vadims06** [comment]
@rinchen i just sent test email and i received it successfully. Please check emaik spelling, or probably i can send you init email and you replay back.

**Comment by rinchen** [comment]
I sent it from two different email providers:
---
 admin@topolograph.com
   550 <admin@topolograph.com> 550 rejected: Unknown recipient :
   previously hard-bounced and is currently blocked. If you think the recipient will no longer hard-bounce they can be unblocked from the 'Reports > Suppressions' page at app.smtp2go.com.
Reporting-MTA: dns; mail.smtp2go.com

Action: failed
Final-Recipient: rfc822;admin@topolograph.com
Status: 5.0.0
---

and

---
<admin@topolograph.com>: host mx2.spaceweb.ru[77.222.41.158] said: 550
   rejected: Unknown recipient (in reply to RCPT TO command)
Reporting-MTA: dns; helm.stanford.tel
X-Postfix-Queue-ID: E3AD43011D6
X-Postfix-Sender: rfc822; joey@stanford.tel
Arrival-Date: Sun,  7 Mar 2021 14:18:08 +0000 (UTC)
Final-Recipient: rfc822; admin@topolograph.com
Original-Recipient: rfc822;admin@topolograph.com

Action: failed
Status: 5.0.0
Remote-MTA: dns; mx2.spaceweb.ru
Diagnostic-Code: smtp; 550 rejected: Unknown recipient
---

**Comment by Vadims06** [comment]
> ## I sent it from two different email providers:
> [admin@topolograph.com](mailto:admin@topolograph.com)
> 550 [admin@topolograph.com](mailto:admin@topolograph.com) 550 rejected: Unknown recipient :
> previously hard-bounced and is currently blocked. If you think the recipient will no longer hard-bounce they can be unblocked from the 'Reports > Suppressions' page at app.smtp2go.com.
> Reporting-MTA: dns; mail.smtp2go.com
> 
> ## Action: failed
> Final-Recipient: rfc822;[admin@topolograph.com](mailto:admin@topolograph.com)
> Status: 5.0.0
> and
> 
> [admin@topolograph.com](mailto:admin@topolograph.com): host mx2.spaceweb.ru[77.222.41.158] said: 550
> rejected: Unknown recipient (in reply to RCPT TO command)
> Reporting-MTA: dns; helm.stanford.tel
> X-Postfix-Queue-ID: E3AD43011D6
> X-Postfix-Sender: rfc822; [joey@stanford.tel](mailto:joey@stanford.tel)
> Arrival-Date: Sun, 7 Mar 2021 14:18:08 +0000 (UTC)
> Final-Recipient: rfc822; [admin@topolograph.com](mailto:admin@topolograph.com)
> Original-Recipient: rfc822;[admin@topolograph.com](mailto:admin@topolograph.com)
> 
> ## Action: failed
> Status: 5.0.0
> Remote-MTA: dns; mx2.spaceweb.ru
> Diagnostic-Code: smtp; 550 rejected: Unknown recipient

Hi @rinchen. Thank you for your email! I am going to create a ticket in my domain hosting provider and additionally i sent to joey@stanford.tel hello email. Please kindly check. I come back as soon as i get any details regarding email error.

**Comment by Vadims06** [comment]
Hi all,
I have just added templates for Mikrotik. Thank you @rinchen for your data. @nlgotz please kindly check too. Single command is only needed - /routing ospf lsa print detail file=lsa.txt

**Comment by archhorde** [comment]
Hello, when I try uploading my lsdb nothing seems to happen. I have tried both the docker desktop version and the website. I used the correct command to generate the lsa.txt file as well. There does not appear to be any debug output or errors to show why it fails. Any help is appreciated!

**Comment by Vadims06** [comment]
> Hello, when I try uploading my lsdb nothing seems to happen. I have tried both the docker desktop version and the website. I used the correct command to generate the lsa.txt file as well. There does not appear to be any debug output or errors to show why it fails. Any help is appreciated!

Hi @archhorde, thank you for your message , could you please send me your file to my email admin@topolograph.com

**Comment by archhorde** [comment]
Hi @Vadims06 , I do not feel comfortable sharing that file as it contains proprietary data. However, I will spin up a lab environment and generate a simple lsdb for debugging purposes. Once I have that I will get back to you.

**Comment by Vadims06** [comment]
> Hi @Vadims06 , I do not feel comfortable sharing that file as it contains proprietary data. However, I will spin up a lab environment and generate a simple lsdb for debugging purposes. Once I have that I will get back to you.

@archhorde sure. Short notice, please make sure that you select Mikrotik radio button during file uploading.

**Comment by archhorde** [comment]
@Vadims06 I have just email you with the file.

**Comment by rinchen** [comment]
If either of you @Vadims06 & @archhorde want me to check that file let me know. I suspect @Vadims06 will be able to figure it out though. @archhorde are you on a relatively current firmware such as 6.48.1?  What device are you using? I probably have one I can export and send to Vadims but the format should be the same.

**Comment by Vadims06** [comment]
Hi Joey @rinchen,
thank you for your openness to help! You were absolutely right, there was a different output depending on Router OS version. Fresh versions (like 6.48.1) print out this row 
`Transit 10.15.5.5 10.15.5.1 10`
but older (6.44.6) - print this
`link-type=Transit id=10.15.5.5 data=10.15.5.1 metric=10`
I adapted templates in order to match even such output.

**Comment by rinchen** [comment]
[Multiple CVEs](https://www.cvedetails.com/vulnerability-list.php?vendor_id=12508&product_id=23641&version_id=0&page=1&hasexp=0&opdos=0&opec=0&opov=0&opcsrf=0&opgpriv=0&opsqli=0&opxss=0&opdirt=0&opmemc=0&ophttprs=0&opbyp=0&opfileinc=0&opginf=0&cvssscoremin=0&cvssscoremax=0&year=0&cweid=0&order=1&trc=17&sha=54982f4894183538bda0bf316e8a38e16187ea4f) for those older versions should I would not recommend running them. 6.47 (LTS) and 6.48 (stable) are the ones people should be running whenever possible.

**Comment by Vadims06** [comment]
Hi @archhorde, does the last update work for you?

**Comment by Vadims06** [comment]
Hi @archhorde , I just released topolograph:v2.17 where added my fixes for 6.44.6 as well as other features, like coloring graph based on host to group (site/office) membership.
Thank you all, I'm always available on the email. Closing this issue,

**Comment by Vadims06** [comment]
Hi @rinchen @nlgotz @archhorde 
I would like to share with you and offer another extension of Topolograph - [OSPF Watcher](https://github.com/Vadims06/ospfwatcher). The watcher connects to a real network via GRE tunnel and logs any changes in the topology. Logs then are exported to Elastic Search stack where can be filtered by the required time period. So you can always find out what has been happening with your topology in the past.

**Comment by rinchen** [comment]
Excellent thanks. I'll have a look. It sounds very useful.
