### ISSUE TITLE
How to set port number for napalm host

### ISSUE THREAD

**Issue by ylopez** [Vadims06/topolograph#9]
Hi, thank you for this project.

I would like to know if it is possible to define the port number when configuring a napalm host.

Cheers
yoann

**Comment by Vadims06** [comment]
Hi @ylopez ,
thank you for your message. I will try to add this functionality. What NAPALM driver do you use?

**Comment by ylopez** [comment]
Hi, I use IOS driver.

**Comment by Vadims06** [comment]
Hi @ylopez, please set PORT number in [docker-compose.override.yml](https://github.com/Vadims06/topolograph-docker/blob/master/docker-compose.override.yml)

**Comment by Vadims06** [comment]
It's better to get LSDB using your favorite tool, like ansible, netmiko and push the LSDB to Topolograph using API
